In [2]:
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np
import math

In [14]:
df  = pd.read_csv("DatasetExos2.csv" , delimiter=";")
df

,ep (ms),Acc_x,Acc_y,Acc_z,Gyro_x,Gyro_y,Gyro_z,ID,Label,Category,Set
0,2019-01-11 15:08:05.200,0.0135,0.977,-0.071,-2.094.366.723,257.720.316,0.9388000000000002,B,bench,heavy,30.0
1,2019-01-11 15:08:05.400,-0.0014999999999999996,0.9704999999999999,-0.07949999999999999,-16.826,-0.8904,21.708,B,bench,heavy,30.0
2,2019-01-11 15:08:05.600,0.0013333333333333333,0.9716666666666667,-0.06433333333333334,526.942.212,-0.2559999999999999,-14.146,B,bench,heavy,30.0
3,2019-01-11 15:08:05.800,-0.024,0.957,-0.0735,8.061,-45.244,-2.073,B,bench,heavy,30.0
4,2019-01-11 15:08:06.000,-0.027999999999999997,0.9576666666666666,-0.115,2.439,-15.486,-36.098,B,bench,heavy,30.0
...,...,...,...,...,...,...,...,...,...,...,...
9004,2019-01-20 17:33:27.000,-0.048,-10.415,-0.0765,14.146,-56.218,0.2926,E,row,medium,40.0
9005,2019-01-20 17:33:27.200,-0.037,1.151.994.539,-0.05333333333333334,-27.684,-0.5854,-1.530.757.122,E,row,medium,40.0
9006,2019-01-20 17:33:27.400,-0.06,274.571.263,-0.08199999999999999,-1.846.542.330,-51.342,-0.12200000000000003,E,row,medium,40.0
9007,2019-01-20 17:33:27.600,-0.03866666666666666,-1.295.977.131,-0.04466666666666667,-0.2318,0.2562,-765.378.561,E,row,medium,40.0
9008,2019-01-20 17:33:27.800,-0.044,-1.034,-0.059,1.098,-4.024,0.976,E,row,medium,40.0

In [15]:
to_numeric = ["Acc_x","Acc_y","Acc_z","Gyro_x","Gyro_y","Gyro_z","Set"]
for i in to_numeric:
    df[i]=pd.to_numeric(df[i],errors="coerce")
df= df.dropna()
df.head()

,ep (ms),Acc_x,Acc_y,Acc_z,Gyro_x,Gyro_y,Gyro_z,ID,Label,Category,Set
1,2019-01-11 15:08:05.400,-0.0015,0.970500,-0.0795,-16.8260,-0.8904,21.708,B,bench,heavy,30.0
3,2019-01-11 15:08:05.800,-0.0240,0.957000,-0.0735,8.0610,-45.2440,-2.073,B,bench,heavy,30.0
4,2019-01-11 15:08:06.000,-0.0280,0.957667,-0.1150,2.4390,-15.4860,-36.098,B,bench,heavy,30.0
5,2019-01-11 15:08:06.200,-0.0260,0.965000,-0.1180,0.4634,52.1940,-64.636,B,bench,heavy,30.0
7,2019-01-11 15:08:06.600,-0.1700,0.899500,-0.2500,175.2460,15.9760,-175.854,B,bench,heavy,30.0

In [16]:
attribute = input("give the attributeyou wanna modify")

1. descretizing Data & Replacing with the average

In [31]:
def labeling(df , intervals , attribute):
    avg = []
    for i in range(len(intervals)-1) :
        df_cals = df[(df[attribute]>intervals[i]) & (df[attribute]<intervals[i+1])]
        avg.append(df_cals[attribute].mean())
    return avg

def descrtizing(df , attribute):
    try : 
        intervals = []
        k = int(1 + (10/3) * math.log10(len(df)))
        max_val = max(df[attribute])
        min_val = min(df[attribute])

        width = (max_val - min_val) / k
        for i in range(k+1):
            intervals.append(min_val)
            min_val+=width
        print("============ INTERVALS ============")
        print(intervals)
        # Store labels as average values ? 
        avg = labeling(df , intervals , attribute)
        
        print("============ AVERAGE ============")
        print(avg)
        df[f"Category {attribute}"]  = pd.cut(df[attribute] , intervals , labels = avg)
        print("============ INFOs ============")
        print(df[f"Category {attribute}"].value_counts())
        print("============ DATA FRAME ============")
        return df
    except Exception as e: 
        print("non numerical values detected")
        print(e)

descrtizing(df , attribute)

============ INTERVALS ============
[-794.392, -671.1743076923077, -547.9566153846154, -424.7389230769231, -301.5212307692308, -178.3035384615385, -55.08584615384619, 68.13184615384611, 191.34953846153843, 314.5672307692307, 437.784923076923, 561.0026153846153, 684.2203076923076, 807.438]
============ AVERAGE ============
[np.float64(-709.3100000000001), np.float64(-620.5893333333333), np.float64(-466.72850000000005), np.float64(-351.8227012987013), np.float64(-225.55198958333332), np.float64(-104.51407660455486), np.float64(3.2835803347280335), np.float64(115.5235286624204), np.float64(241.19032608695653), np.float64(363.3346333333333), np.float64(483.7652903225806), np.float64(624.1547142857142), np.float64(749.627)]
============ INFOs ============
Category Gyro_z
 3.283580      2390
-104.514077     483
 115.523529     471
-225.551990     192
 241.190326     184
 363.334633     120
-351.822701      77
 483.765290      31
-466.728500      28
 624.154714      14
 749.627000      10
-620.589333       6
-709.310000       3
Name: count, dtype: int64
============ DATA FRAME ============

C:\Users\abdo7\AppData\Local\Temp\ipykernel_3260\1350402335.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f"Category {attribute}"]  = pd.cut(df[attribute] , intervals , labels = avg)

,ep (ms),Acc_x,Acc_y,Acc_z,Gyro_x,Gyro_y,Gyro_z,ID,Label,Category,Set,Category Gyro_z
1,2019-01-11 15:08:05.400,-0.001500,0.970500,-0.0795,-16.8260,-0.8904,21.7080,B,bench,heavy,30.0,3.283580
3,2019-01-11 15:08:05.800,-0.024000,0.957000,-0.0735,8.0610,-45.2440,-2.0730,B,bench,heavy,30.0,3.283580
4,2019-01-11 15:08:06.000,-0.028000,0.957667,-0.1150,2.4390,-15.4860,-36.0980,B,bench,heavy,30.0,3.283580
5,2019-01-11 15:08:06.200,-0.026000,0.965000,-0.1180,0.4634,52.1940,-64.6360,B,bench,heavy,30.0,-104.514077
7,2019-01-11 15:08:06.600,-0.170000,0.899500,-0.2500,175.2460,15.9760,-175.8540,B,bench,heavy,30.0,-104.514077
...,...,...,...,...,...,...,...,...,...,...,...,...
8986,2019-01-20 17:33:23.400,-0.051500,-1.055000,-0.0860,-1.3780,-64.1480,6.0610,E,row,medium,40.0,3.283580
8988,2019-01-20 17:33:23.800,0.001500,-12.685000,-0.0030,426.8280,-0.4390,-22.2440,E,row,medium,40.0,3.283580
8999,2019-01-20 17:33:26.000,0.023333,-0.483667,0.2000,-87.9260,93.6580,0.1342,E,row,medium,40.0,3.283580
9004,2019-01-20 17:33:27.000,-0.048000,-10.415000,-0.0765,14.1460,-56.2180,0.2926,E,row,medium,40.0,3.283580
9008,2019-01-20 17:33:27.800,-0.044000,-1.034000,-0.0590,1.0980,-4.0240,0.9760,E,row,medium,40.0,3.283580

3. Normalization

In [56]:
def normalization(x , minimum , maximum):
    normalized = (x - minimum)/(maximum - minimum)
    return normalized
columns  = [i for i in df.columns if df[i].dtype == "float64"]
for i in columns : 
    df[i] = df[i].apply(lambda x : normalization(x , min(df[i]) , max(df[i])))
df

,ep (ms),Acc_x,Acc_y,Acc_z,Gyro_x,Gyro_y,Gyro_z,ID,Label,Category,Set,Category Gyro_z
1,2019-01-11 15:08:05.400,0.071136,0.503762,0.287338,0.446616,0.487965,0.509480,B,bench,heavy,0.315217,6.523000
3,2019-01-11 15:08:05.800,0.069069,0.503322,0.291127,0.460166,0.464658,0.494634,B,bench,heavy,0.315217,6.523000
4,2019-01-11 15:08:06.000,0.068701,0.503344,0.264919,0.457105,0.480295,0.473392,B,bench,heavy,0.315217,6.523000
5,2019-01-11 15:08:06.200,0.068885,0.503583,0.263025,0.456030,0.515859,0.455576,B,bench,heavy,0.315217,-116.694692
7,2019-01-11 15:08:06.600,0.055650,0.501450,0.179665,0.551197,0.496828,0.386145,B,bench,heavy,0.315217,-116.694692
...,...,...,...,...,...,...,...,...,...,...,...,...
8986,2019-01-20 17:33:23.400,0.066541,0.437785,0.283233,0.455027,0.454725,0.499712,E,row,medium,0.423913,6.523000
8988,2019-01-20 17:33:23.800,0.071412,0.058958,0.335649,0.688180,0.488202,0.482041,E,row,medium,0.423913,6.523000
8999,2019-01-20 17:33:26.000,0.073419,0.456395,0.463846,0.407902,0.537647,0.496012,E,row,medium,0.423913,6.523000
9004,2019-01-20 17:33:27.000,0.066863,0.132899,0.289233,0.463480,0.458892,0.496110,E,row,medium,0.423913,6.523000
9008,2019-01-20 17:33:27.800,0.067230,0.438469,0.300284,0.456375,0.486318,0.496537,E,row,medium,0.423913,6.523000